import type { Metadata } from "next";
import "./globals.css";
import FormProvider from "@/context/FormProvider";

export const metadata: Metadata = {
  title: "Sadrivia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="bg-gray-100">
        <FormProvider>
          {children}
        </FormProvider>
      </body>
    </html>
  );
}
